/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'outline':                    '#7b7583',
        'surface-dim':                '#dadad8',
        'error-container':            '#ffdad6',
        'on-tertiary-fixed-variant':  '#792b45',
        'on-error':                   '#ffffff',
        'on-primary':                 '#ffffff',
        'inverse-primary':            '#d2bcff',
        'surface-container-high':     '#e9e8e6',
        'surface':                    '#faf9f7',
        'on-background':              '#1a1c1b',
        'secondary':                  '#894b62',
        'tertiary-fixed-dim':         '#ffb1c4',
        'error':                      '#ba1a1a',
        'on-surface-variant':         '#494551',
        'background':                 '#faf9f7',
        'tertiary':                   '#8b3953',
        'on-secondary-fixed':         '#38081f',
        'secondary-container':        '#ffb0cb',
        'inverse-surface':            '#2f3130',
        'inverse-on-surface':         '#f1f1ef',
        'surface-container':          '#efeeec',
        'on-primary-fixed':           '#25005a',
        'secondary-fixed':            '#ffd9e3',
        'primary-container':          '#7b5bbe',
        'outline-variant':            '#cbc3d3',
        'surface-bright':             '#faf9f7',
        'on-surface':                 '#1a1c1b',
        'surface-container-highest':  '#e3e2e0',
        'on-secondary-container':     '#7b3f56',
        'surface-container-lowest':   '#ffffff',
        'primary-fixed-dim':          '#d2bcff',
        'on-secondary':               '#ffffff',
        'primary':                    '#6242a3',
        'on-tertiary':                '#ffffff',
        'primary-fixed':              '#eaddff',
        'surface-container-low':      '#f4f3f1',
        'surface-tint':               '#6b4bad',
        'tertiary-fixed':             '#ffd9e0',
        'on-tertiary-container':      '#ffecef',
        'on-primary-container':       '#f7eeff',
        'on-error-container':         '#93000a',
        'on-primary-fixed-variant':   '#533294',
        'tertiary-container':         '#a9516b',
        'surface-variant':            '#e3e2e0',
        'on-secondary-fixed-variant': '#6d344a',
        'secondary-fixed-dim':        '#ffb0cb',
        'gold-accent':                '#D4AF37',
      },
      fontFamily: {
        headline:      ['"Cormorant Garamond"', 'serif'],
        'serif-alt':   ['Playfair Display', 'serif'],
        body:          ['"DM Sans"', 'sans-serif'],
        label:         ['Montserrat', 'sans-serif'],
        sans:          ['"DM Sans"', 'system-ui', 'sans-serif'],
        display:       ['"Cormorant Garamond"', 'serif'],
        editorial:     ['"Cormorant Garamond"', 'serif'],
        accent:        ['Playfair Display', 'serif'],
        'sans-modern': ['"DM Sans"', 'sans-serif'],
        brand:         ['Montserrat', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0rem',
        sm:      '0rem',
        md:      '0rem',
        lg:      '0rem',
        xl:      '0rem',
        '2xl':   '0rem',
        '3xl':   '0rem',
        full:    '9999px',
      },
    },
  },
  plugins: [],
};
