/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'outline':                    'rgb(var(--c-outline) / <alpha-value>)',
        'surface-dim':                'rgb(var(--c-surface-dim) / <alpha-value>)',
        'error-container':            'rgb(var(--c-error-container) / <alpha-value>)',
        'on-tertiary-fixed-variant':  'rgb(var(--c-on-tertiary-fixed-variant) / <alpha-value>)',
        'on-error':                   'rgb(var(--c-on-error) / <alpha-value>)',
        'on-primary':                 'rgb(var(--c-on-primary) / <alpha-value>)',
        'inverse-primary':            'rgb(var(--c-inverse-primary) / <alpha-value>)',
        'surface-container-high':     'rgb(var(--c-surface-container-high) / <alpha-value>)',
        'surface':                    'rgb(var(--c-surface) / <alpha-value>)',
        'on-background':              'rgb(var(--c-on-background) / <alpha-value>)',
        'secondary':                  'rgb(var(--c-secondary) / <alpha-value>)',
        'tertiary-fixed-dim':         'rgb(var(--c-tertiary-fixed-dim) / <alpha-value>)',
        'error':                      'rgb(var(--c-error) / <alpha-value>)',
        'on-surface-variant':         'rgb(var(--c-on-surface-variant) / <alpha-value>)',
        'background':                 'rgb(var(--c-background) / <alpha-value>)',
        'tertiary':                   'rgb(var(--c-tertiary) / <alpha-value>)',
        'on-secondary-fixed':         'rgb(var(--c-on-secondary-fixed) / <alpha-value>)',
        'secondary-container':        'rgb(var(--c-secondary-container) / <alpha-value>)',
        'inverse-surface':            'rgb(var(--c-inverse-surface) / <alpha-value>)',
        'inverse-on-surface':         'rgb(var(--c-inverse-on-surface) / <alpha-value>)',
        'surface-container':          'rgb(var(--c-surface-container) / <alpha-value>)',
        'on-primary-fixed':           'rgb(var(--c-on-primary-fixed) / <alpha-value>)',
        'secondary-fixed':            'rgb(var(--c-secondary-fixed) / <alpha-value>)',
        'primary-container':          'rgb(var(--c-primary-container) / <alpha-value>)',
        'outline-variant':            'rgb(var(--c-outline-variant) / <alpha-value>)',
        'surface-bright':             'rgb(var(--c-surface-bright) / <alpha-value>)',
        'on-surface':                 'rgb(var(--c-on-surface) / <alpha-value>)',
        'surface-container-highest':  'rgb(var(--c-surface-container-highest) / <alpha-value>)',
        'on-secondary-container':     'rgb(var(--c-on-secondary-container) / <alpha-value>)',
        'surface-container-lowest':   'rgb(var(--c-surface-container-lowest) / <alpha-value>)',
        'primary-fixed-dim':          'rgb(var(--c-primary-fixed-dim) / <alpha-value>)',
        'on-secondary':               'rgb(var(--c-on-secondary) / <alpha-value>)',
        'primary':                    'rgb(var(--c-primary) / <alpha-value>)',
        'on-tertiary':                'rgb(var(--c-on-tertiary) / <alpha-value>)',
        'primary-fixed':              'rgb(var(--c-primary-fixed) / <alpha-value>)',
        'surface-container-low':      'rgb(var(--c-surface-container-low) / <alpha-value>)',
        'surface-tint':               'rgb(var(--c-surface-tint) / <alpha-value>)',
        'tertiary-fixed':             'rgb(var(--c-tertiary-fixed) / <alpha-value>)',
        'on-tertiary-container':      'rgb(var(--c-on-tertiary-container) / <alpha-value>)',
        'on-primary-container':       'rgb(var(--c-on-primary-container) / <alpha-value>)',
        'on-error-container':         'rgb(var(--c-on-error-container) / <alpha-value>)',
        'on-primary-fixed-variant':   'rgb(var(--c-on-primary-fixed-variant) / <alpha-value>)',
        'tertiary-container':         'rgb(var(--c-tertiary-container) / <alpha-value>)',
        'surface-variant':            'rgb(var(--c-surface-variant) / <alpha-value>)',
        'on-secondary-fixed-variant': 'rgb(var(--c-on-secondary-fixed-variant) / <alpha-value>)',
        'secondary-fixed-dim':        'rgb(var(--c-secondary-fixed-dim) / <alpha-value>)',
        'gold-accent':                'rgb(var(--c-gold-accent) / <alpha-value>)',
      },
      fontFamily: {
        headline:      ['"Cormorant Garamond"', 'serif'],
        'serif-alt':   ['Playfair Display', 'serif'],
        body:          ['"DM Sans"', 'sans-serif'],
        label:         ['Montserrat', 'sans-serif'],
        sans:          ['"DM Sans"', 'system-ui', 'sans-serif'],
        display:       ['"Cormorant Garamond"', 'serif'],
        editorial:     ['"Cormorant Garamond"', 'serif'],
        accent:        ['Playfair Display', 'serif'],
        'sans-modern': ['"DM Sans"', 'sans-serif'],
        brand:         ['Montserrat', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0rem',
        sm:      '0rem',
        md:      '0rem',
        lg:      '0rem',
        xl:      '0rem',
        '2xl':   '0rem',
        '3xl':   '0rem',
        full:    '9999px',
      },
    },
  },
  plugins: [],
};
